create table if not exists public.tips (
  id bigint generated by default as identity primary key,
  situation text not null,
  tried_text text not null,
  effect text not null,
  stutter_type text not null,
  created_at timestamptz not null default now()
);

alter table public.tips enable row level security;

create policy "Anyone can read tips"
on public.tips
for select
to anon
using (true);

create policy "Anyone can insert tips"
on public.tips
for insert
to anon
with check (true);

create table if not exists public.tip_reports (
  id bigint generated by default as identity primary key,
  tip_id bigint not null references public.tips(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.tip_reports enable row level security;

create policy "Anyone can insert reports"
on public.tip_reports
for insert
to anon
with check (true);
